### ISSUE TITLE
Chalk Blanking On Windows

### ISSUE THREAD

**Issue by paulxtiseo** [chalk/chalk#161] opened 2017-06-26 23:58 UTC
For some reason, not sure if it's just my box, but Chalk fails to show any formatting in `ConEmu` or `Cmder` and usually everything goes blank, even the subsequent command-line in `ConEmu`. In `cmd.exe`, it shows the white-on-black basic text.

For example:
```
let showHelp = function() {
  console.log();
  console.log(chalk.bold('Usage:') + '   rfx-tool migrate {subcommand} {target} [options]\n');
  console.log(chalk.bold('Description:') + ' ' + this.description);
  
  console.log('\nup: pushes (deploys) uncommitted migrations to the target');
  let data = [
    {option: '-a, --all', description: 'pushes all uncommitted migrations; default is to push next undeployed migration'},
    {option: '-c <path>, --config=<number>', description: 'path to file with connection data; defaults to /local/migrate.json'},
    {option: '-s <number>, --steps=<number>', description: 'pushes <number> undeployed migration files'},
    {option: '-v, --verbose', description: 'verbose console logging'},
  ];
  console.log(columnify(data, {showHeaders: false}));

  console.log('\ndown: pulls (reverses) migrations in the target');
  data = [
    {option: '-a, --all', description: 'pulls all committed migrations; default is to pull last committed migration'},
    {option: '-c <path>, --config=<number>', description: 'path to file with connection data; defaults to /local/migrate.json'},
    {option: '-s <number>, --steps=<number>', description: 'pulls <number> committed migration files'},
    {option: '-v, --verbose', description: 'verbose console logging'},
  ];
  console.log(columnify(data, {showHeaders: false}));
};
```

in `Cmder` shows:
```
E:\
λ rfx-tool migrate help

Summary: 
Usage:

Description:













E:\
λ
```

If I select the area with mouse and cursor, the text shows up in the highlight, so it's there, but invisible. In `ConEmu`, the command line is likewise blanked, as if `Cmder` resets itself at each new command line , but `Conemu` doesn't.

Wha?

**Comment by Qix-** [comment] 2017-06-27 03:13
Hi!

Windows version/build (build _is_ important)? Can you double-check your chalk version? Could you post some screenshots?

Certain builds of Windows 10 have been finicky since the whole "Bash On Windows" thing. My gut reaction is this is a bug in their code.

Thanks!

**Comment by paulxtiseo** [comment] 2017-06-27 03:25
Microsoft Windows 10 Professional (x64) Build 15063.413 (RS2)
Chalk is v1.1.3

**Comment by paulxtiseo** [comment] 2017-06-27 03:26
Here's a screenshot in ConEmu:

![2017-06-26 23_23_07-cmd](https://user-images.githubusercontent.com/2977050/27569671-c912df30-5ac6-11e7-9915-c3e65f05e97d.png)

The text is there:
![2017-06-26 23_26_12-cmd](https://user-images.githubusercontent.com/2977050/27569690-e33bdb6e-5ac6-11e7-8b0e-e0f48f31f872.png)

**Comment by Qix-** [comment] 2017-06-27 03:48
Very strange. Can you run the following node.js commands in the Node.js REPL and post a screenshot?

```javascript
console.log('\x1b[31mhello\x1b[m there')
console.log('\x1b[31mhello\x1b[0m there')
console.log('\x1b[31mhello\x1b[39m there')
console.log('\x1b[1mhello\x1b[m there')
console.log('\x1b[1mhello\x1b[0m there')
console.log('\x1b[1mhello\x1b[22m there')
console.log('\x1b[1mhello\x1b[21m there')
console.log('\x1b[2mhello\x1b[m there')
console.log('\x1b[2mhello\x1b[0m there')
console.log('\x1b[2mhello\x1b[22m there')
console.log('\x1b[2mhello\x1b[21m there')
```

**Comment by paulxtiseo** [comment] 2017-06-27 11:36
![2017-06-27 07_35_59-cmd - node](https://user-images.githubusercontent.com/2977050/27585697-4c1b45e0-5b0b-11e7-9406-bca73fb1d11a.png)

**Comment by Qix-** [comment] 2017-06-27 19:02
Perhaps @Maximus5 would be able to give some insight, as this is showing inconsistent behavior in ConEmu. I've not seen anything similar to this re: chalk or even Node's handling on Windows.

**Comment by Maximus5** [comment] 2017-06-27 20:52
The main question is: does ConEmu receive ANSI sequences? I think it doesn't.
Like cygwin and msys, chalk may use its own-implemented tty converter to use native WinAPI.

**Comment by Qix-** [comment] 2017-06-27 21:37
@Maximus5 I don't know, does it? On some of the latest builds of Windows, ANSI sequences are supported natively, which means [LibUV](https://github.com/libuv/libuv) (Node.js' underlying I/O abstraction layer) doesn't step in and convert them to the `Console*` functions.

So it could be that ConEmu doesn't support ANSI codes whereas Node.js is emitting them since the underlying version (more specifically, the build) is high enough.

**Comment by Maximus5** [comment] 2017-06-27 21:50
ConEmu may log all data written by console application to CONIN$.
http://conemu.github.io/en/SettingsFeatures.html#id2679

I'm pretty sure there would be no ANSI sequences.

**Comment by Qix-** [comment] 2017-06-27 22:04
I'm not sure I'm following; the Windows console _does_ support ANSI codes as of Windows 10 build 10586.

ConEmu should forward them along.

**Comment by Maximus5** [comment] 2017-06-27 23:09
It's not absolutely correct.
ConEmu does process ANSI internally. If console application does not write ANSI, that obviously means that neither ConEmu nor Win10 conhost receive them. Therefore console application use WinAPI instead of writing ANSI.

**Comment by Qix-** [comment] 2017-06-27 23:40
@Maximus5 But the OP here _is_ writing ansi codes.

**Comment by sindresorhus** [comment] 2017-06-28 00:47
Closing as it's not really related to Chalk. It's either a problem with Libuv (used in Node.js) or ConEmu. Most likely the latter.

Feel free to continue the discussion here.

**Closed by sindresorhus** 2017-06-28 00:47 UTC

**Comment by borekb** [comment] 2017-10-07 19:33
I'm seeing something similar, the problem is specifically when I try to set background color. My code is also combined with [execa](https://github.com/sindresorhus/execa) and piping the output to stdout:

```js
for (const module of modules) {

    console.log(chalk.bgCyan(`--- ${module} ---`));

    const execaObject = execa('...');
    execaObject.stdout.pipe(process.stdout);
    execaObject.stderr.pipe(process.stderr);
    await execaObject;
}
```

![image](https://user-images.githubusercontent.com/101152/31311167-b3289896-aba6-11e7-87f9-d40e2b178789.png)

Just changing `chalk.bgCyan` to `chalk.cyan` in the code fixes it:

![image](https://user-images.githubusercontent.com/101152/31311154-7c81d348-aba6-11e7-8b31-de59288b8961.png)

**Comment by borekb** [comment] 2017-10-07 19:34
Also, when the entire program finishes and I scroll up, the "missing text" is back, rendered correctly in white. I don't know what to make of it.

**Comment by borekb** [comment] 2017-10-07 19:38
Oh, also `chalk.black.bgCyan` fixes it, I didn't realize foreground has to be set explicitly. Maybe the original issue is that chalk is trying to set a high-contrast value when only bg color is provided and then doesn't reset back?

**Comment by Qix-** [comment] 2017-10-12 18:26
> Also, when the entire program finishes and I scroll up, the "missing text" is back, rendered correctly in white. I don't know what to make of it.

This is 100% a problem in your terminal emulator of choice, and you should file a bug with them instead :)

Out of curiosity, which one are you using?

**Comment by borekb** [comment] 2017-10-29 21:04
@Qix- You're right, I'm using ConEmu / cmder most of the time which is where the screenshots are from. In VSCode terminal, everything is alright. Strange because ConEmu is very stable compared to other terminal emulators I've tried.
