### ISSUE TITLE
Generate Random Color

### ISSUE THREAD

**Issue by sujeet-agrahari** [chalk/chalk#384] opened 2020-02-22 07:22 UTC
I am running a `forEach()` loop, and I need to `console.log()`. But I want to get a different color for each iteration. I went trhough docs, but couldn't find anything. Is there any way possible to achieve the same?

```
let arr = ["a", "ab, "abc"]
arr.forEach(arr, e => {
  console.log(chalk.red(e)) //maybe something like - chalk.randColor()
})
```

**Comment by sindresorhus** [comment] 2020-02-22 07:55
Duplicate of #353

**Closed by sindresorhus** 2020-02-22 07:55 UTC
