### ISSUE TITLE
2.1.0 release Breaking/Broken

### ISSUE THREAD

**Issue by bdistin** [chalk/chalk#195] opened 2017-08-09 15:30 UTC
Platform: Windows Server 2012 R2
Console: Cmder
Node Version: v8.1.4

Example code that worked before 2.1.0 release:
```javascript
const chalk = require('chalk');
const clk = new chalk.constructor({ enabled: true });

console.log(`${clk.bgBlue("Text with blue background")}${clk.bgMagenta("Text with magenta background")} ect`);
```
2.0.1:
![image](https://puu.sh/x5M0s/72fd220417.png)

2.1.0:
![image](https://puu.sh/x5LOu/cf3cc1d8c2.png)

**Comment by Qix-** [comment] 2017-08-09 16:20
What happens when you call `chalk.constructor` without `new`?

**Comment by bdistin** [comment] 2017-08-09 16:43
```javascript
const chalk = require('chalk');
const clk = chalk.constructor({ enabled: true });

console.log(`${clk.bgBlue("Text with blue background")}${clk.bgMagenta("Text with magenta background")} ect`);
```
Same results for both versions. If the above is what you mean.
```javascript
const chalk = require('chalk');

console.log(`${chalk.bgBlue("Text with blue background")}${chalk.bgMagenta("Text with magenta background")} ect`);
```
Neither versions work with this code. (which was why the added chalk constructor enabled...)

**Comment by Qix-** [comment] 2017-08-09 17:20
Ah yeah we might have changed something in supports-color. I'll investigate.

**Comment by bdistin** [comment] 2017-08-12 00:59
update: Bug only occurs while using forever.js

**Comment by Qix-** [comment] 2017-08-12 22:23
That might be your problem. Forever.js might be using pipes or IPC for output. This will cause `supports-color` to not output color codes and thus is a problem on their end.

**Comment by bdistin** [comment] 2017-08-12 23:49
Like I said though, it works up until the last release. Forever.js didn't change (hasn't since late '16).

**Comment by kyranet** [comment] 2017-08-17 07:15
I can reproduce this same issue, but in PM2. Using Chalk@2.1.0:
![image](https://user-images.githubusercontent.com/24852502/29400127-4f14d84e-832c-11e7-8c81-136a67f105fd.png)
And in Chalk@2.0.1
![image](https://user-images.githubusercontent.com/24852502/29400139-5e6bd720-832c-11e7-8c73-60eb4576776c.png)

**OS:** Ubuntu 16.04 LTS x64
**Console:** PuTTY (I'm in SSH)
**Node.js Version:** 8.3.0

**Comment by Qix-** [comment] 2017-08-17 09:32
These all sound like cases where Chalk is actually functioning properly - unless I'm mistaken, these wrappers for chalk-enabled applications are using pipes, which would cause `isatty` to return false.

Does `FORCE_COLOR=1` still work for you?

**Comment by kyranet** [comment] 2017-08-17 11:55
Evaluating `process.stdout.isTTY` returned `undefined` in PM2 and the value for `process.stdout._type` is pipe, however, in a normal Node.js process, the first returned `true` and `_type` is `tty`:

The returned value of `console.log(process.stdout);` with PM2:

```javascript
Socket {
  connecting: false,
  _hadError: false,
  _handle: [Object],
  _parent: null,
  _host: null,
  _readableState: [Object],
  readable: false,
  domain: null,
  _events: [Object],
  _eventsCount: 3,
  _maxListeners: undefined,
  _writableState: [Object],
  writable: true,
  allowHalfOpen: false,
  _bytesDispatched: 528,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  _type: 'pipe',
  fd: 1,
  _isStdio: true,
  destroySoon: [Object],
  _destroy: [Object],
  [Symbol(asyncId)]: 10,
  [Symbol(bytesRead)]: 0 }
```

The returned value of `console.log(process.stdout);` without PM2:

```javascript
WriteStream {
  connecting: false,
  _hadError: false,
  _handle: [Object],
  _parent: null,
  _host: null,
  _readableState: [Object],
  readable: false,
  domain: null,
  _events: [Object],
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState: [Object],
  writable: true,
  allowHalfOpen: false,
  _bytesDispatched: 100,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  columns: 238, 
  rows: 61,
  _type: 'tty',
  fd: 1,
  _isStdio: true,
  destroySoon: [Function: destroy],
  _destroy: [Function],
  [Symbol(asyncId)]: 2,
  [Symbol(bytesRead)]: 0 }
```

**Comment by Qix-** [comment] 2017-08-17 14:44
Thank you for the detailed info @kyranet - does the environment variable `FORCE_COLOR=1` enable colors?

**Comment by CyberiumShadow** [comment] 2017-08-21 02:33
@Qix- Just tested using similar environments to @bdistin and @kyranet 

Using the `FORCE_COLOR=1` env var enables colors.

**Comment by Qix-** [comment] 2017-08-21 02:42
Thanks for the confirm @CyberiumShadow.

Yeah, to be honest it sounds like `supports-color` was broken before v2 - this is actually intended behavior.

Please use `FORCE_COLOR=1` if you need it. Remember that any time you run your script inside of a wrapper (e.g. PM2) where it spawns a new node process, it's most likely going to cause `isatty()` to return `0` under the hood, causing `process.stdout.isTTY` to be `false`-ey.

You're more than welcome to file a ticket over at PM2 to use pseudo-terminals upon spawning, but IIRC that's a ton of work from the Node.js end and not cross-platform compatible.

Closing unless someone has reason to believe this is unintended functionality.

**Closed by Qix-** 2017-08-21 02:42 UTC
