### ISSUE TITLE
Very strange async problem

### ISSUE THREAD

**Issue by lukeapage** [chalk/chalk#80] opened 2015-08-16 12:26 UTC
I'm getting a strange problem when the first use of chalk is in an async callback thread.
Node 0.12.6

```
[ReferenceError: builder is not defined]
ReferenceError: builder is not defined
    at Chalk.builder (c:\git\node-markdown-spellcheck\node_modules\chalk\index.js:40:27)
    at c:\git\node-markdown-spellcheck\es5\cli.js:221:58
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:187:20
    at iterate (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:265:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:284:9)
    at Object.async.forEachSeries.async.eachSeries (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:220:22)
    at c:\git\node-markdown-spellcheck\es5\cli.js:219:26
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:697:13
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:52:16
    at done (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:248:21)
```

I've looked at the code

```
	var builder = function builder() {
		return applyStyle.apply(builder, arguments);
	};
```

and I've no idea why it is going wrong - the function expression name should be exposed.

If I change the chalk code in my node_modules to...

```
	var builder = function () {
		return applyStyle.apply(builder, arguments);
	};
```

then it works.

If I add a dummy call to chalk before I start doing async things, it works

```
chalk.red("red"); // fix very weird bug
```

The only explanation I have is that its a weird V8 bug. I'm raising here in case there is something I missed, or you have seen it before or you had been thinking about removing the function name anyway.

**Comment by lukeapage** [comment] 2015-08-16 12:30
I've tried reproducing with
```
var chalk = require("chalk");
setTimeout(function() {
"use strict";
chalk.red("red");
}, 100);
```

but no luck. It seems even in my `node-markdown-spellcheck` it only happens if it successfully reads a file before using chalk and async is fired async.

**Comment by Qix-** [comment] 2015-08-17 04:50
This sounds like a conflict with another package. Can you list the packages you're using, or do you have your package on NPM so I could take a look?

**Comment by lukeapage** [comment] 2015-08-17 07:24
```
async@1.4.2 node_modules\async

hunspell-spellchecker@1.0.2 node_modules\hunspell-spellchecker

marked@0.3.5 node_modules\marked

commander@2.8.1 node_modules\commander
└── graceful-readlink@1.0.1

chalk@1.1.0 node_modules\chalk
├── escape-string-regexp@1.0.3
├── supports-color@2.0.0
├── ansi-styles@2.1.0
├── strip-ansi@3.0.0 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

glob@5.0.14 node_modules\glob
├── path-is-absolute@1.0.0
├── inherits@2.0.1
├── once@1.3.2 (wrappy@1.0.1)
├── inflight@1.0.4 (wrappy@1.0.1)
└── minimatch@2.0.10 (brace-expansion@1.1.0)

inquirer@0.9.0 node_modules\inquirer
├── figures@1.3.5
├── strip-ansi@3.0.0
├── ansi-regex@2.0.0
├── cli-width@1.0.1
├── through@2.3.8
├── run-async@0.1.0 (once@1.3.2)
├── readline2@0.1.1 (mute-stream@0.0.4, strip-ansi@2.0.1)
├── rx-lite@2.5.2
└── lodash@3.10.1
```

Looking at the source code I cannot see how something else could cause this...

**Comment by Qix-** [comment] 2015-08-17 14:30
Unfortunately I cannot reproduce this.

```javascript
var fs = require('fs');
var chalk = require('chalk');
require('async');
require('hunspell-spellchecker');
require('marked');
require('commander');
require('glob');
require('inquirer');

var file = fs.readFileSync('./foo');
setTimeout(function() {
  console.log(chalk.blue("Hi?"));
}, 500);
```

Successfully outputs a blue string.

```
 $ node --version
v0.12.6
$ node index.js
Hi?
```

Can you start chipping pieces away until you have a small piece of code that reproduces the error? Also, what platform are you on?

**Comment by lukeapage** [comment] 2015-08-17 14:44
windows, node 0.12.6.

Looking at the source code it can *only* be a V8 bug in node 0.12.0 - the code is valid

**Comment by Qix-** [comment] 2015-08-17 14:50
I think more specifically, it could very well be a bug in the Windows build. Can you try downgrading to 0.12.0 to see if the bug is still present?

**Comment by alexbeletsky** [comment] 2015-08-19 15:11
Having the same problem, mentioned here - https://github.com/sindresorhus/time-grunt/issues/66

Mac OS X, node v0.12.5.

Even if I removed `time-grunt` usage, now my `uglify` grunt task if failing,

```
Running "uglify:main" (uglify) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js
Warning: builder is not defined Use --force to continue.
ReferenceError: builder is not defined
    at Chalk.builder (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/node_modules/chalk/index.js:40:27)
    at /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js:176:45
    at Array.forEach (native)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js:63:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:227:11
```

In `uglify`,

```js
      grunt.verbose.writeln('File ' + chalk.cyan(f.dest) + ' created: ' +
        maxmin(result.max, output, options.report === 'gzip'));
```

That's pretty serious for me. Any help will be really appreciated.

**Comment by lukeapage** [comment] 2015-08-19 15:50
The only fix I had was to edit the files in `node_modules/xxx/chalk/index.js` https://github.com/chalk/chalk/blob/6142553bb5d7b3e7fbcea76b8ccf876f373e1bf1/index.js#L39 and remove the name from the function expression.

it *must* be an obscure V8 bug effecting `0.12` and effecting chalk only in very specific scenarios.

**Comment by lukeapage** [comment] 2015-08-19 15:59
I've made a PR with that fix. I can't see a reason not to fix it, since the code is equivalent, but doesn't randomly fail for at least people >= 2 .

@alexbeletsky I forgot the fix I put in my repo might help you too - https://github.com/lukeapage/node-markdown-spellcheck/blob/master/es6/cli.js#L37

**Comment by alexbeletsky** [comment] 2015-08-19 16:09
hey @lukeapage thanks a lot for this! I hope PR is merged as soon as possible.

**Comment by Qix-** [comment] 2015-08-19 16:12
@lukeapage as I mentioned in the PR (and I'll mention here for completeness), can either you or @alexbeletsky provide some code that reproduces this?

**Comment by lukeapage** [comment] 2015-08-19 17:58
@caitp, knowing you work on V8, does this bug ring a bell with you? I've searched the V8 issues and I can't see a named function expression bug that has been raised or fixed recently

**Comment by Qix-** [comment] 2015-08-19 19:49
Reproduced; like 90% sure this is indeed a V8/Node bug.

**Comment by caitp** [comment] 2015-08-19 19:57
@lukeapage on phone but I'll take a look in a minute. I might need to see a bit more code

**Closed** 2015-08-19 19:57 UTC

**Comment by caitp** [comment] 2015-08-19 20:03
based on the snippets i'm seeing, it could be a V8 bug or it could be user error (more context is needed to be sure). If you give me instructions for reproducing, I can probably narrow it down a bit more

**Comment by lukeapage** [comment] 2015-08-19 20:04
@caitp if you are interested,  thanks,  it seems pretty weird (though we do have a workaround). 
the code creating the error is here:
https://github.com/chalk/chalk/blob/6142553bb5d7b3e7fbcea76b8ccf876f373e1bf1/index.js#L39
reproduce steps are on the pr, I've spent an hour trying to make a small reproduction repo without luck.

**Comment by lukeapage** [comment] 2015-08-19 20:05
I'm interested enough to try something else if you have any pointers.

**Comment by lukeapage** [comment] 2015-08-19 20:07
link to repro steps : https://github.com/chalk/chalk/pull/81#issuecomment-132716911

**Comment by caitp** [comment] 2015-08-19 20:21
I can reproduce this in node 0.11 and 0.12, but not 3.0 --- so if this was a bug upstream, it seems to have been fixed at some point. It seems to work with flag `--nolazy`, so presumably this was a parsing bug.

**Comment by lukeapage** [comment] 2015-08-19 20:29
Thanks @caitp
