### ISSUE TITLE
No .ansi256 in 256-color level; .apply not safe

### ISSUE THREAD

**Issue by diegojsRW** [chalk/chalk#224] opened 2017-11-03 06:57 UTC
Hello.

When running this code on Windows Command Prompt:

```
console.log(chalk.ansi256(ansiColor)(whateverString));
```

I get this error:
```
E:\Projetos\outros\teste_sl\geralargos\node_modules\chalk\index.js:82
                                const open = ansiStyles.color[levelMapping[level]][model].apply(null, arguments);
                                                                                         ^

TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (E:\Projetos\outros\teste_sl\geralargos\node_modules\chalk\index.js:82:62)
    at slimes.forEach.slime (E:\Projetos\outros\teste_sl\geralargos\index.js:75:75)
    at Array.forEach (<anonymous>)
    at parseFile (E:\Projetos\outros\teste_sl\geralargos\index.js:72:12)
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

So I tried to debug that particular line and found something.
`levelMapping` contains an ordered array with four elements: "ansi", "ansi", "ansi256" and "ansi16m", respectively 0,1,2 and 3. 
`level` contains the number representing current terminal's color level.
`model` contains the function name of the used color model.
`ansiStyles.color` contains all the named foreground and background colors "constants" (i.e. they contain start and end closure declarations), as well as groups called "ansi", "ansi256" and "ansi16m".
Occurred that, in "256 colors" mode, there is no function called ansi256, whereas both "ansi16m" and "ansi" does have it. And, as it is dynamically defined by current level, there is no checking of existence of object `ansiStyles.color[levelMapping[level]][model]` on line 82.

So, why 256 color mode lacks `ansi256` function? 
And the calling to `.apply` there is not safe.

**Comment by Qix-** [comment] 2017-11-04 19:38
I can't reproduce.

![image](https://user-images.githubusercontent.com/885648/32408839-f1dc6fba-c15c-11e7-906c-2eb99409d6b8.png)


I'm not sure about what you're describing either - it's worked for millions of people for months now. Which version of node are you on? Which version of chalk are you running?

**Comment by diegojsRW** [comment] 2017-11-04 23:51
Sending a printscreen.
![image](https://user-images.githubusercontent.com/2223939/32410560-4ac1f79c-c1aa-11e7-806c-99019c1266ed.png)

**Comment by partheseas** [comment] 2017-11-23 21:02
I have this issue on Windows as well. Is there any possibility, but the working screenshot looks like a Unix shell. Is there any chance this is a platform specific issue?

**Comment by danfuzz** [comment] 2018-02-06 17:20
This looks like it might be related to issue #248.

**Comment by partheseas** [comment] 2018-02-06 18:59
@danfuzz It absolutely is. This is actually an issue with the underlying support library that chalk uses, chalk/ansi-styles. I applied a band aid fix for this issue (that still hasn't been merged in. *sigh* open source amirite?) but it looks like it's a deeper rooted issue that affects several API's.

**Closed** 2018-03-02 17:43 UTC
