### ISSUE TITLE
2.2 appears to be a breaking changes version?

### ISSUE THREAD

**Issue by johnnyreilly** [chalk/chalk#219] opened 2017-10-20 12:42 UTC
We upgrade ts-loader to Chalk 2.2 and upon release we started to get reports of errors: https://github.com/TypeStrong/ts-loader/issues/664

Is 2.2 actually breaking changes?

**Comment by Qix-** [comment] 2017-10-20 19:25
Shouldn't be. The user on your issue sounds like they had some version mismatch. Pinning wouldn't have solved the problem if 2.2 was a breaking change.

**Comment by sindresorhus** [comment] 2017-10-20 19:31
Duplicate of #215

**Closed by sindresorhus** 2017-10-20 19:31 UTC
Labels: question

**Comment by johnnyreilly** [comment] 2017-10-20 23:07
We released v 3.0.5  of ts-loader which required 2.2 chalk as a minimum. Hopefully that should resolve all issues
