### ISSUE TITLE
`chalk@1.1.3` does not include commits from `chalk@1.1.2`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [chalk/chalk#135] opened 2016-10-20 16:43 UTC
[The commits for 1.1.3](https://github.com/chalk/chalk/commits/v1.1.3) don't seem to include all of [the commits for 1.1.2](https://github.com/chalk/chalk/commits/v1.1.2).  I think that's why the package from npm seems to pull `supports-color@2.0.0`.

**Comment by sindresorhus** [comment] 2016-10-20 16:54
Duplicate of https://github.com/chalk/chalk/issues/110.

**Closed by sindresorhus** 2016-10-20 16:54 UTC

**Comment by wtgtybhertgeghgtwtg** [comment] 2016-10-20 17:03
Sorry about that.
