### ISSUE TITLE
[BUG] chalk.hex crashes when color is not supported

### ISSUE THREAD

**Issue by bokub** [chalk/chalk#178] opened 2017-07-20 17:51 UTC
On a terminal where color is not supported, when I run the following code:

```javascript
console.log('supportsColor:', chalk.supportsColor);
chalk.hex('ff5f6d')('A');
```

I get the following output:

```
supportsColor: false

X:\Boris\gradient-string\node_modules\chalk\index.js:75
    const open = ansiStyles.color[levelMapping[level]][model].apply(null, arguments);
                                                      ^

TypeError: Cannot read property 'hex' of undefined
    at Function.<anonymous> (X:\Boris\gradient-string\node_modules\chalk\index.js:75:55)

```

I guess the expected result would be a white string (without any color), am I right?

N.B: as you can see, I run this on a Windows machine 😕

**Comment by Qix-** [comment] 2017-07-21 18:41
Duplicate of #176.

**Closed by Qix-** 2017-07-21 18:41 UTC
