### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined => bgBlack?

### ISSUE THREAD

**Issue by ORESoftware** [chalk/chalk#208] opened 2017-09-10 23:35 UTC
I swear bgBlack is available

but when I do this:

`chalk.bgBlack.white.bold()`

I get:

`TypeError: Cannot read property 'bold' of undefined`

**Comment by Qix-** [comment] 2017-09-11 06:03
Hey there, I can't reproduce this.

```javascript
> chalk.bgBlack.white.bold('hello')
'\u001b[40m\u001b[37m\u001b[1mhello\u001b[22m\u001b[39m\u001b[49m'
```

**Comment by sindresorhus** [comment] 2017-09-11 07:57
Which npm version are you using? Make sure you're using the latest one.

**Comment by ORESoftware** [comment] 2017-09-11 07:59
weird, thx, let me re-investigage

**Comment by LitoMore** [comment] 2017-09-11 09:06
@ORESoftware `Cannot read property 'bold' of undefined` means that `chalk.bgBlack.white` is `undefined`, **NOT** `chalk.bgBlack` is `undefined`.

You need to swear `chalk.bgBlack.white` is available. :)

**Comment by ORESoftware** [comment] 2017-09-11 09:39
@LitoMore thaz true

**Comment by sindresorhus** [comment] 2018-02-11 12:53
Closing as it's most likely an npm issue.

**Closed by sindresorhus** 2018-02-11 12:53 UTC

**Comment by sandip2224** [comment] 2021-11-03 03:26
In my case I had forgotten this statement: 
```
const colors=require('colors')
```
This solved my issue.

**Comment by j-dogcoder** [comment] 2022-02-24 22:54
Also having this issue

**Comment by Qix-** [comment] 2022-10-10 13:50
Please open a new issue then with all relevant information. This is a 5 year old issue about a very old version of Chalk.
