### ISSUE TITLE
Semantic API

### ISSUE THREAD

**Issue by fuchao2012** [chalk/chalk#199] opened 2017-08-17 07:47 UTC
As describe in title.

Can we add some semantic API like `link`, `title` `comment` ...

```
chalk.link = chalk.blue.bold.underline
```

**Comment by Qix-** [comment] 2017-08-17 11:27
There's nothing stopping you from doing this. What's the problem you're facing?

**Comment by Qix-** [comment] 2017-08-17 11:29
Also, this is a duplicate of #190.

**Comment by Qix-** [comment] 2017-08-17 11:30
Duplicate of #190.

**Closed** 2017-08-20 02:25 UTC
