### ISSUE TITLE
Yellow color does not work in Windows PowerShell

### ISSUE THREAD

**Issue by simondel** [chalk/chalk#155] opened 2017-06-03 13:50 UTC
PowerShell has recently become the default shell in Windows, which means that most Windows users will start using it in the near future. However, yellow text does not work in Windows PowerShell, it shows up as being white.

**Comment by sindresorhus** [comment] 2017-06-03 14:35
Duplicate of https://github.com/chalk/chalk/issues/2

**Closed by sindresorhus** 2017-06-03 14:35 UTC
