### ISSUE TITLE
Detect if the terminal theme is light or dark

### ISSUE THREAD

**Issue by andygongea** [chalk/chalk#497] opened 2021-07-07 13:28 UTC
It would be very useful to know the type of theme (light/dark) the terminal has.

In this way the dev can properly set the colors:
- for light background to have dark colors
- for dark background to have light colors

Currently if you want to specify even the generic colors Chalk provides, you end up with unusable ouput because the user might have a theme that do not work well with the colors.

**Comment by sindresorhus** [comment] 2021-07-07 13:43
AFAIK, there's no standardized way to detect this, unless you try to add custom detection for every single terminal, which is not feasible. This is why using the named color methods (for example, `chalk.red(…)`) is recommended. They will correctly adapt to the color theme.

I agree it would be useful though. If you want to see this happen, I suggest you open an issue on some popular terminals to get this going. It could be a standardized environment variable that terminals expose.

Some more info: https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color?noredirect=1&lq=1

**Comment by sindresorhus** [comment] 2021-07-07 13:43
Duplicate of #272

**Closed by sindresorhus** 2021-07-07 13:43 UTC
