### ISSUE TITLE
Chalk 2.0.0 (and above) not working in IE11 with webpack 4

### ISSUE THREAD

**Issue by web-surfer** [chalk/chalk#280] opened 2018-06-27 00:48 UTC
I'm currently using webpack 4 (may or may not be relevant), and I'm not able to get my project to load in IE11 when I have any version of Chalk installed that is above version 2.0.0 (Chalk version 1.0.0 through 1.1.3 work fine with IE11 and webpack 4).

The error is coming from here:
**../node_modules/chalk/index.js [Line: 5029, Col: 1], main.bundle.js**

Specifically, the error in the IE11 console states:
**{exception}	Const must be initialized**

This is happening with all versions of Chalk above 2.0.0, but _not_ with versions 1.0.0 through 1.1.3.

**Comment by sindresorhus** [comment] 2018-06-27 01:55
Duplicate of #245

**Closed by sindresorhus** 2018-06-27 01:55 UTC
